name: CI/CD
on: [ push, pull_request ]
jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - name: build
        env: 
          PUBLIC_URL: /resume
        run: |
          npm ci --force
          npm run build:web
          npm run build:pdf
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build
      - name: Upload resume
        uses: actions/upload-artifact@v2
        with:
          name: resume-en
          path: |
            build/alfredo-salzillo-resume.pdf
